services:
  reflective:
    image: "ghcr.io/beingflo/reflective:0.1.23"
    container_name: reflective
    ports:
      - 3005:3001
    env_file: "service/.env.prod"
    restart: unless-stopped
    depends_on:
      - reflective-db
    networks:
      - caddy_net
      - reflective_net
      - events_net

  reflective-db:
    image: postgres:17
    container_name: reflective-db
    env_file: ".env.prod"
    networks:
      - reflective_net
    ports:
      - 5434:5432
    volumes:
      - reflective-pg:/var/lib/postgresql/data/
    restart: unless-stopped

  pg_backup:
    container_name: reflective-backup
    build:
      dockerfile: ./backup/Dockerfile
    restart: unless-stopped
    env_file: ".env.prod"
    depends_on:
      - reflective-db
    networks:
      - reflective_net
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.reflective-backup.schedule: "@daily"
      ofelia.job-exec.reflective-backup.command: "./backup.sh"

networks:
  caddy_net:
    external: true
  reflective_net:
    name: reflective_net
  events_net:
    external: true

volumes:
  reflective-pg:
    name: "reflective-pg"
