services:
  reflective:
    image: "ghcr.io/beingflo/reflective:0.1.7"
    container_name: reflective
    ports:
      - 3005:3001
    env_file: "service/.env.prod"
    restart: unless-stopped
    depends_on:
      - reflective-db
    networks:
      - caddy_net
      - reflective_net

  reflective-db:
    image: postgres:latest
    container_name: reflective-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reflective
    networks:
      - reflective_net
    ports:
      - 5434:5432
    volumes:
      - ~/reflective/db/:/var/lib/postgresql/data/
    restart: unless-stopped

networks:
  caddy_net:
    external: true
  reflective_net:
    name: reflective_net
