services:
  reflective:
    image: "ghcr.io/beingflo/reflective:0.1.2"
    container_name: reflective
    ports:
      - 3005:3001
    env_file: "service/.env.prod"
    restart: unless-stopped
    depends_on:
      - reflective-db
    networks:
      - caddy_net

  reflective-db:
    image: postgres:latest
    container_name: reflective-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reflective
    ports:
      - 5434:5432
    volumes:
      - ~/tmp/postgres:/var/lib/postgresql/data/
    restart: unless-stopped

networks:
  caddy_net:
    external: true
